name: Generate Pac-Man

on:
  schedule:
    - cron: "0 1 * * *"   # jalan otomatis tiap jam 01:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate light Pac-Man graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: CiaOfii
          output_path: dist/pacman-contribution-graph.svg
          dark_mode: false

      - name: Generate dark Pac-Man graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: CiaOfii
          output_path: dist/pacman-contribution-graph-dark.svg
          dark_mode: true

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
